spring:
  profiles:
    active: dev
  application:
    name: hrms
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true

jwt:
  expirationMs: ${JWT_EXPIRATION_MS:86400000} # 24 hours default

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
